// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hv_4w9nwWe_4kFdzCPt6cdKJVo8rSG0',
    appId: '1:628516372658:web:b0be27b53b94e2fcadc9ab',
    messagingSenderId: '628516372658',
    projectId: 'minichat-app-cb2c0',
    authDomain: 'minichat-app-cb2c0.firebaseapp.com',
    storageBucket: 'minichat-app-cb2c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAenz37-momQyJ4i5UJWhinAB_--A631gc',
    appId: '1:628516372658:android:651056d711dc35a5adc9ab',
    messagingSenderId: '628516372658',
    projectId: 'minichat-app-cb2c0',
    storageBucket: 'minichat-app-cb2c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB73W7UTRjZXnxHxisD2a5aRkb2bPxnNYY',
    appId: '1:628516372658:ios:d691432e83dcf215adc9ab',
    messagingSenderId: '628516372658',
    projectId: 'minichat-app-cb2c0',
    storageBucket: 'minichat-app-cb2c0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB73W7UTRjZXnxHxisD2a5aRkb2bPxnNYY',
    appId: '1:628516372658:ios:d691432e83dcf215adc9ab',
    messagingSenderId: '628516372658',
    projectId: 'minichat-app-cb2c0',
    storageBucket: 'minichat-app-cb2c0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9hv_4w9nwWe_4kFdzCPt6cdKJVo8rSG0',
    appId: '1:628516372658:web:57e5708ee2e8f6f6adc9ab',
    messagingSenderId: '628516372658',
    projectId: 'minichat-app-cb2c0',
    authDomain: 'minichat-app-cb2c0.firebaseapp.com',
    storageBucket: 'minichat-app-cb2c0.firebasestorage.app',
  );
}
